apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: flux-system
  labels:
    app: nginx  
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.app: docker.io/gunahk/flux-dem:test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        fluxcd.io/automated: "true"
        fluxcd.io/tag.app: docker.io/gunahk/flux-dem:test
    spec:
      containers:
      - name: nginx
        image: docker.io/gunahk/flux-dem:test
        ports:
        - containerPort: 80
