apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: flux-system
  labels:
    app: nginx
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.app: docker.io/gunahk/flux-dem:main
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        fluxcd.io/automated: "true"
        fluxcd.io/tag.app: docker.io/gunahk/flux-dem:main
    spec:
      containers:
        - name: nginx
          image: docker.io/gunahk/flux-dem:main-ce0834ee47a7289e5c5555944284999109bed9d7 # {"$imagepolicy": "flux-system:dockerhub-tag-policy"}
          ports:
            - containerPort: 80
