name: Manually triggered workflow

on:
  push:
    branches:
      - main



jobs:
  dev-deploy:
    name: Deploy-dev-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Generate build ID
      id: prepasdfdf
      run: |
        echo ${{ github.event.label.name }}
        
        
    - name: Generate build ID
      if: ${{ github.event.label.name == 'skip-BG' }}
      id: prepasasdfsfff
      run: |
        echo ${{ github.event.label.name }}
    
    
