name: Manually triggered workflow

on:
  push:
    branches:
      - main

jobs:
  dev-deploy:
    name: Deploy-dev-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Generate build ID
      id: prepasdfdf
      run: |
        echo ${{ github.event.label.name }}


    - name: build image 
      id: build-image
      env:
          ECR_REPOSITORY: ECR_REPOSITORY
          ECR_REGISTRY: ECR_REGISTRY
          IMAGE_TAG: IMAGE_TAG
      run: |
          echo "docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ."
          IMAGE_NAME=::add-mask::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=IMAGE_NAME::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "::set-output name=IMAGE_TAG::$IMAGE_TAG"
          
    - name: push image 
      id: push-image
      run: |
          echo IMAGE_NAME=${IMAGE_NAME}
          echo "docker push ${IMAGE_NAME}"
          echo "::set-output name=IMAGE_NAME::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "::set-output name=IMAGE_TAG::$IMAGE_TAG"
