name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run.'
        required: true
        default: 'prod-deploy'
jobs:
  dev-deploy:
    name: Deploy dev-deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'yaml'}}
    steps:
    - name: Generate build ID
      id: prep
      run: |
        branch=${GITHUB_REF##*/}
        git_sha=${GITHUB_SHA::4}
        time_stamp=$(TZ=":Asia/Kolkata" date +%Y-%m-%d-%H-%M-%S)
        echo "::set-output name=BUILD_ID::${branch}-${git_sha}-${time_stamp}"
        echo "IMAGE_TAG=${branch}-${git_sha}-${time_stamp}" >> $GITHUB_ENV


  prod-deploy:
    name: Deploy prod-deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'yaml'}}
    needs: dev-deploy
    steps:
    - name: Generate build ID
      id: prep
      run: |
        echo ${IMAGE_TAG}
        
