name: Manually triggered workflow

on:
  push:
    branches:
      - main

jobs:
  dev-deploy:
    name: Deploy-dev-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Generate build ID
      id: prepasdfdf
      run: |
        echo ${{ github.event.label.name }}

    - name: Dump GitHub context
      if: endsWith(github.ref, '/deploy-develop')
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
      
    - name: Check PR labels action step
      id: check_pr_labels
      if: endsWith(github.ref, '/main')
      uses: shioyang/check-pr-labels-on-push-action@v1.0.3
      with:
        github-token: ${{ env.HELM_GIT_SECRET }}
        labels: '["skip-blue-green"]'

    - name: Generate build ID
      if: endsWith(github.ref, '/main') && steps.check_pr_labels.outputs.result == 'true'
      id: prepasasdfsfff
      run: |
        echo ${{ github.event.label.name }}
        echo "you are correct"
    
    
