name: Manually triggered workflow

on:
  push:
    branches:
      - main

jobs:
  dev-deploy:
    name: Deploy-dev-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Generate build ID
      id: prep
      env: 
        IMAGE_TAG: ${GITHUB_REF##*/}-${GITHUB_SHA::4}-$(TZ=":Asia/Kolkata" date +%Y-%m-%d-%H-%M-%S)
      run: |
        echo "::set-output name=IMAGE_TAG::$IMAGE_TAG"
    outputs:
      IMAGE_TAG: "${{ steps.prep.outputs.IMAGE_TAG }}"

  prod-deploy:
    name: Deploy-prod-deploy
    runs-on: ubuntu-latest
    needs: dev-deploy
    steps:
    - name: Generate build ID
      id: prep
      run: |
        echo "+++++++++++++++"
        echo ${{ needs.dev-deploy.outputs.IMAGE_TAG }}
