name: Manually triggered workflow

on:
  push:
    branches:
      - main

jobs:
  dev-deploy:
    name: Deploy-dev-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Generate build ID
      id: prep
      run: |
        branch=${GITHUB_REF##*/}
        git_sha=${GITHUB_SHA::4}
        time_stamp=$(TZ=":Asia/Kolkata" date +%Y-%m-%d-%H-%M-%S)
        echo "::set-output name=BUILD_ID::${branch}-${git_sha}-${time_stamp}"
        echo "BUILD_ID=${branch}-${git_sha}-${time_stamp}">>${GITHUB_ENV}
        echo "+++++++++++++++"
        echo ${BUILD_ID}
        echo "+++++++++++++++"
    outputs:
      BUILD_ID: "${{ steps.prep.outputs.BUILD_ID }}"

  prod-deploy:
    name: Deploy-prod-deploy
    runs-on: ubuntu-latest
    needs: dev-deploy
    steps:
    - name: Generate build ID
      id: prep
      run: |
        echo "+++++++++++++++"
        echo ${{ dev-deploy.outputs.BUILD_ID }}
